### ISSUE TITLE
Refactor Image_registration

### ISSUE THREAD

**Issue by BennyGinger** [BennyGinger/ImageAnalysis_pipeline#1]
The channel shift transformation matrix is now calculated from the first Image of both channels and then applied to every other frame.

**Comment by BennyGinger** [comment]
Both @SamHawkens2 and @BennyGinger corrected the function separately... I'm still learning how to communicate I guess. So to be sorted :)

**Comment by BennyGinger** [comment]
@SamHawkens2 I'll keep my version, if you don't mind, since I'm working on the tmats extraction as well.

**Comment by SamHawkens2** [comment]
Absolutely!

**Comment by BennyGinger** [comment]
I now fully refactor image registration and tested it on small sample size. So far so good. I might test it a bit more, but for me it's a done.
