### ISSUE TITLE
Dealing with numpy/nd2reader dependencies

### ISSUE THREAD

**Issue by BennyGinger** [BennyGinger/ImageAnalysis_pipeline#2]
numpy==1.22.4 has an error in one of its packages. _distance is not being imported. Updated version i.e. 1.24.4 is working properly.

With newer numpy versions, nd2 reader has an issue, beacuse np.float is not longer supported but can easily fixed. Can we load package from a issue branch? r change to "https://github.com/tlambert03/nd2" as an alternative since this is still maintained. Otherwise numpy 1.23 seems to be working working.

**Comment by SamHawkens2** [comment]
basic work is done by adding a function to read and save all the needed metadata. One function for writing the image sequence using the old ND2Reader is still left. I would like to have some input here @BennyGinger , how we want to deal with that function. 

Basically, we can only call a single frame with the new nd2 reader based on the index value of the loaded nd2 objectarray.

**Comment by BennyGinger** [comment]
You will have to show me, but it sounds like it's the same as the old one. I had to write a for loop to extract all the images, based on the x and y (image size), frame, channel (if any), z (if any) and field of view (if any).

**Comment by SamHawkens2** [comment]
Everyting added and need to be tested. Especially the different channel extraction.

**Comment by BennyGinger** [comment]
Ok I've tested it and it failed... I couldn't write the images. Like the loops when through without any errors, except that there were no images at the end in the folder. After investigation, I found that the read_frame(get_frame()) didn't work. So I made some modifications: mainly I extract the whole stack at once and go through it as we do with tiff. I know it defeats the purpose of extracting frame by frame, especially if we are talking about huge stack, but I think now all or machine in the lab can deal with loading big stack once, especially if we don't process them.
Anyway, it's now super fast to create an image seq (~0.7 s on my laptop and 0.04s on my machine at work...) and everything is running smoothly. So I'll close this for now

**Comment by SamHawkens2** [comment]
My version is commited and working. I diabled the userwarnings for opening several nd2_objects during the parallel process. But we have to give the object to several cores, otherwise there is no multiprocessing. I tried as well to only have one object as a global object, but that failed during the parallelprocess as well.

**Comment by BennyGinger** [comment]
@SamHawkens2 I've finished with the refactor with your code. I struggled a bit with the get_frame, so I had to modify it a bit. I've tested a bit on my laptop and it worked now.
I've also added a checkpoint where if the image is larger than 20GB then it will use the ND2file extraction, otherwise it will use the array extraction.
I've committed it on the main2.0_dev, could you now test it on your big files? I don't have access to any here and let me know if it worked.

Side note: Can you also have a look at the bg_sub function with big files. I've just noticed today that this step requires almost 70% of my RAM. It's running on multi-process, so I'm hoping that even if the file is big, it will stop at ~70% anyway, but I don't know. Anyway, let me know if it works.

**Comment by SamHawkens2** [comment]
Image_Sequencing in working fine with the big files. It takes a lot of time and to abort we will have to restart the kernel. But thats fine in my opinion. 
I did not check the bg_sub yet.
