### ISSUE TITLE
morph function crash

### ISSUE THREAD

**Issue by SamHawkens2** [BennyGinger/ImageAnalysis_pipeline#5]
While running the morph function called from the iou tracking, the kernel of jupyter is crashing and we result with no mask.
Already tried: update to a newer version of numpy. this was the first thought of the error. 

Please see the error message as reference.

![Image](https://github.com/BennyGinger/ImageAnalysis_pipeline/assets/101874356/a2a414eb-a386-4205-9af1-9da0f261296f)

**Comment by BennyGinger** [comment]
It was because of dependencies (how surprising...), but it's now fixed, when using nd2 instead of nd2reader.
