### ISSUE TITLE
return transformation matrix

### ISSUE THREAD

**Issue by BennyGinger** [BennyGinger/ImageAnalysis_pipeline#6]
would be good to be able to return the transformation matrix file form the images registration

**Comment by BennyGinger** [comment]
@SamHawkens2 can you remind me why you need the tmats? and which tmats do you need exactly? because for the frame shift registration, there will be one tmats for each images... Do you need them all?

**Comment by SamHawkens2** [comment]
Only the one from the final image registration is needed, not from the channel shift. We have some manual tracked data, which are tracked in an non registered image. And we can use that by  registering this by using the same that's as the resulting images

**Comment by BennyGinger** [comment]
Then you need a bunch of them... OK I was first thinking saving them in the exp_setting file, but now I think I'll have to hard save them...

**Comment by BennyGinger** [comment]
> Only the one from the final image registration is needed, not from the channel shift. We have some manual tracked data, which are tracked in an non registered image. And we can use that by registering this by using the same that's as the resulting images

Hum @SamHawkens2 just add a thought last night. If it's something that is not going to be mainstream (that is, normally it will be done on registered images) then why don't we do it manually with Fiji? You can save the tmats and then apply it to your mask, no?

I could do it within the pipeline, but I don't think we will need it, more than once or twice... What do you think?

**Comment by SamHawkens2** [comment]
Absolutly! We do not need to apply the tmats on the mask later. This is done manually. Only to save the tmats would be great to have a toggle.

**Comment by BennyGinger** [comment]
We agree with @SamHawkens2 that this can be done manually, no need to change the output.
