### ISSUE TITLE
Multi-threading bug

### ISSUE THREAD

**Issue by BennyGinger** [BennyGinger/ImageAnalysis_pipeline#8]
Hi @SamHawkens2 and @flini20,

I've encountered some issue with the multi-threading. With my old env, when I run the code, all CPU are recruited. Now with the newly env only 2 at a time... I thought it was first because I was running it from docker, but after installing it on my computer, I got the same. So somehow, there is/are a pkg(s) that limit the access to my CPU... Now the fun part would be to identify it/them...

So first question, do you see the same issue on your machine as well? Like if you run the image sequence for like an exp of about 1000 frames (in total, including txyzc) it takes me about 18 sec on my computer (I know it might a bit different depending on your hardware) with the old env and 1.2 min with the new one...

and second question any suggestions of how to proceed?

**Comment by SamHawkens2** [comment]
I'll have a look over the weekend if I see something.

**Comment by BennyGinger** [comment]
So I identified the source, and unfortunately it's cp3... So I've opened an issue on Cellpose, to see whether they have an idea or not how to solve it, but for now I think we should use cp2.

@SamHawkens2 @flini20 would it be a pb for the gui? Which version are you using now?

**Comment by BennyGinger** [comment]
OK, it turned out that it's not cellpose but pytorch the culprit. By default, pytorch pre-configure the interpreter, which will enter in conflict with any multiprocessing. So, I now force all multiprocessing to start new interpreter, and not inherit parent ones... Therefore, removing pytorch configuration...

So for now this is solved for me, and hopefully, this won't have an impact on cellpose itself, while running
